hmrc/ers-checking-frontend

app/views/check_csv_file.scala.html, app/views/check_file.scala.html, app/views/check_file_type.scala.html, app/views/checking_success.scala.html, app/views/error_report.scala.html, app/views/format_errors.scala.html, app/views/html_error_report.scala.html, app/views/not_authorised.scala.html, app/views/scheme_type.scala.html, app/views/service_unavailable.scala.html, app/views/start.scala.html, app/views/templates/header.scala.html, conf/app.routes, conf/messages
=> Change tab titles

public/stylesheets/ers_styles.css
[ERS-2640] - Fix css media styles
=> Fix css media styles

conf/messages
=> fix tab titles

conf/messages, public/stylesheets/ers_styles.css
=> Increase font size for error table

app/views/check_csv_file.scala.html, app/views/check_file.scala.html, app/views/check_file_type.scala.html, app/views/ers_main.scala.html, app/views/helpers/error_overview.scala.html, app/views/scheme_type.scala.html, public/javascripts/ers_csv_scripts.js, public/javascripts/ers_ods_scripts.js, public/javascripts/ers_scripts.js, public/stylesheets/ers_styles.css
=> fix error focus

app/utils/ExternalUrls.scala, conf/application.conf
[ERS-2666] - Change of all sign in URLs to a single MDTP login page
=> Change of all sign in URLs to a single MDTP login page

conf/validation-config/OTHER/ers-other-options-validation.conf, test/services/validation/OTHERTestData/ERSValidationOTHEROptionsTestData.scala
[ERS-2672] - Update validation and remove error messages
=> Update validation and remove error messages

app/config/AppConfig.scala, app/views/error_template.scala.html, app/views/global_error.scala.html, app/views/main.scala.html, conf/application.conf, project/FrontendBuild.scala
=> DDCNLS-427 upgrades for simplified assets

app/utils/HtmlCreator.scala, app/views/check_csv_file.scala.html, app/views/check_file.scala.html, app/views/html_error_report.scala.html, app/views/scheme_type.scala.html, conf/messages
DDCNLS-1554:ERS message file refactor
=> DDCNLS-1554:ERS message file refactor

conf/messages
@nehakannaujia - one test aborted - repeats in master;  you'll need to review. Apart from that, everything is okay.
=> DDCNLS-1555 Contractions and smart quotes

conf/logback.xml
Changing name of the service as per github in the log file
=> Changing name of the service as per github

app/Module.scala, app/config/ApplicationConfig.scala, app/controllers/LanguageSwitchController.scala, app/views/main.scala.html, conf/app.routes, conf/application.conf, conf/messages.cy, project/FrontendBuild.scala, test/controllers/LanguageSwitchControllerTest.scala
adds ability to toggle welsh language
=> DDCNLS-4760

conf/application.conf
=> DDCNLS-WelshToggleOn

app/controllers/HtmlReportController.scala, project/MicroService.scala, test/controllers/HtmlReportControllerTest.scala, test/controllers/UpscanControllerSpec.scala
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).
- Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?
- Have you done a visual check of the changes?
- Is there any still commented or unused code? Lingering printlns?
- Have things been implemented in a complicated way?
- Are the test still over the coverage threshold?
- Does the compiler throw a lot of warnings? 
- Have methods and tests been named clearly?
- Were there any changes in the config? Do changes need to be made in app-config-???
- Have you done a manual walkthrough?
=> DDDCE-1013: added some missing tests and some tidy up

conf/application.conf, project/FrontendBuild.scala, test/controllers/CheckingServiceControllerTest.scala, test/controllers/HtmlReportControllerTest.scala
Here, as a part of the ticket DDCE-1082 a new feature has been added as per which it is checked if the url for accessibility statements is present in the ers checks service.
- Have you looked at the JIRA story to make sure all Acceptance Criteria has been met? Yes
- Have you done a visual check of the changes? Yes
- Is there any still commented or unused code? Lingering printlns? No
- Have things been implemented in a complicated way? No
- Are the test still over the coverage threshold? No
- Does the compiler throw a lot of warnings? No
- Have methods and tests been named clearly? N/a
- Were there any changes in the config? Do changes need to be made in app-config-??? No
- Have you done a manual walkthrough? Yes
=> DDCE-1082:Implement accessibility statement for ERS-Checking-Frontend

app/config/ApplicationConfig.scala, conf/application.conf
The get help form was failing against the CSP and not actually working. This is because we were using base url which isn't easily overwritten in environments that aren't local. Creating the 'baseurl' locally under a single config value and overwriting that in environments is the standard way.
BEFORE MERGING, THE APP CONFIG BASE PR MUST BE MERGED AND ALLOWED TO BUILD FIRST! -- PR HERE -- https://github.com/hmrc/app-config-base/pull/4186
- Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?
- Have you done a visual check of the changes?
- Is there any still commented or unused code? Lingering printlns?
- Have things been implemented in a complicated way?
- Are the test still over the coverage threshold?
- Does the compiler throw a lot of warnings? 
- Have …
=> DDCE-1110: Fixed get help form

app/connectors/UpscanConnector.scala
Removed the agent name from the upscan connector which was adding a duplicate service name causing the call to fail
- Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?
- Have you done a visual check of the changes?
- Is there any still commented or unused code? Lingering printlns?
- Have things been implemented in a complicated way?
- Are the test still over the coverage threshold?
- Does the compiler throw a lot of warnings? 
- Have methods and tests been named clearly?
- Were there any changes in the config? Do changes need to be made in app-config-???
- Have you done a manual walkthrough?
=> removed agent header name from upscan connector

app/config/ApplicationConfig.scala, app/views/main.scala.html, conf/application.conf
Introducing gtm to the service
- Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?
- Have you done a visual check of the changes?
- Is there any still commented or unused code? Lingering printlns?
- Have things been implemented in a complicated way?
- Are the test still over the coverage threshold?
- Does the compiler throw a lot of warnings? 
- Have methods and tests been named clearly?
- Were there any changes in the config? Do changes need to be made in app-config-???
- Have you done a manual walkthrough?
=> DDCE-1074: added gtm config and to the views

app/controllers/UpscanController.scala, app/controllers/internal/UpscanCallbackController.scala, app/services/audit/AuditService.scala, app/utils/CacheUtil.scala
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).
=> DDCE-1364:Update log timestamps to readable format

app/config/ApplicationConfig.scala, app/views/global_error.scala.html, app/views/includes/commonScriptElements.scala.html, app/views/main.scala.html, conf/application.conf
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).
- [x ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
- [x ]  I've executed the acceptance test pack locally to ensure there are no functional regressions (Performance tests where relevant)
- [x ]  I've squashed my commits - including the JIRA issue number in the commit message
- []  I've run a dependency check to ensure all dependencies are up to date
=> DDCE-1517: tracking consent banner

conf/application.conf
Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs, context or links to other PRs related to this PR (eg. acceptance tests, environment config).
=> [DDCE] update ods success cache config to match returns

conf/application-json-logger.xml, conf/application.conf
Small change to enable logs in Production after the move to the `Logging` trait
=> [EH][DDCE-Logs] Enable environment specific logging configuration

app/views/check_csv_file.scala.html, app/views/ers_main.scala.html, app/views/includes/upscan_file_upload_form.scala.html, build.sbt, conf/application.conf, conf/logback.xml, conf/messages, conf/messages.cy, test/controllers/AuthorisationControllerSpec.scala, test/helpers/ErsTestHelper.scala
~~Currently awaiting design and welsh sign-off but otherwise is ready~~
Has been signed off by both!
- Add timeout dialogue
- Change titles on csv upload pages
- Add labels for upload button
=> [DP][DDCE-1687] Fix accessibility issues (A)

app/controllers/UpscanController.scala, app/views/file_upload_problem.scala.html, conf/messages, conf/messages.cy, test/controllers/Fixtures.scala, test/controllers/UpscanControllerSpec.scala
Update error messages to a show a generic 4xx page in case javascript is disabled on the browser
=> [DDCE-2053][SD] Update error scenario handling if javascript is disabled

public/javascripts/ers_csv_scripts.js, public/javascripts/ers_ods_scripts.js, public/javascripts/ers_scripts.js, public/javascripts/welsh_translation.js
DDCE-2388
Removed .csv and .ods filename type checking
=> DDCE-2388 - Remove checks for file type CSV or ODS for file upload

app/controllers/CheckingServiceController.scala, app/controllers/UploadController.scala, app/controllers/UpscanController.scala, app/services/DataGenerator.scala, build.sbt, project/AppDependencies.scala, project/build.properties, project/plugins.sbt, test/controllers/CheckingServiceControllerTest.scala, test/controllers/UploadControllerTest.scala, test/controllers/UpscanControllerSpec.scala, test/services/audit/AuditEventsTest.scala, test/services/audit/AuditServiceTest.scala
Also adjusted some logs and fixed various compiler warnings
=> [DP][DDCE-3067] Bootstrap & sbt upgrades

app/views/ers_main.scala.html
Cookies banner was previously displayed twice. This will fix it.
=> DDCE-3993 | Fixed double cookies banner.

app/connectors/UpscanConnector.scala, app/views/ers_main.scala.html, test/connectors/UpscanConnectorSpec.scala
DDCE-4928 - replacing deprecated HmrcLayout to HmrcStandardPage
=> DDCE-4928 - replacing deprecated HmrcLayout to HmrcStandardPage

conf/messages.cy, conf/messages.en
DDCE-6365 -[ERS] Remove references to forms on the checking service
=> DDCE-6365 -[ERS] Remove references to forms on the checking service

app/views/start.scala.html, conf/messages.cy, conf/messages.en
Ddce 3616: Update contents across service
=> Ddce 3616: Update contents across service

a11y/FrontendAccessibilitySpec.scala, app/views/not_enrolled_in_paye.scala.html, conf/messages.cy, conf/messages.en, test/controllers/CheckCsvFilesControllerSpec.scala, test/controllers/CheckingServiceControllerTest.scala, test/controllers/Fixtures.scala
DDCE-6593: Fix full stop issue from the link
=> DDCE-6593: Fix full stop issue from the link
